name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Test Package bruno-query
        run: npm run test --workspace=packages/bruno-query
      - name: Test Package bruno-lang
        run: npm run test --workspace=packages/bruno-lang
      - name: Test Package bruno-schema
        run: npm run test --workspace=packages/bruno-schema
      - name: Test Package bruno-app
        run: npm run test --workspace=packages/bruno-app

      # bruno-js needs bruno-query to be built first
      - name: Build Package bruno-query
        run: npm build test --workspace=packages/bruno-query
      - name: Test Package bruno-js
        run: npm run test --workspace=packages/bruno-js

      - name: Test Package bruno-common
        run: npm run test --workspace=packages/bruno-common
      - name: Test Package bruno-cli
        run: npm run test --workspace=packages/bruno-cli
      - name: Test Package bruno-electron
        run: npm run test --workspace=packages/bruno-electron

  cli-test:
    name: Run Bruno CLI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and run tests
        run: |
          cd packages/bruno-tests/collection
          node ../../bruno-cli/bin/bru.js run --env Prod --output junit.xml --format junit

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report
          path: sanity/collection/junit.xml
          reporter: java-junit

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run Prettier
        run: npm run test:prettier:web
